### Getlanguages (GET)
GET http://localhost:3000/api/languages

### Getlanguages (POST)
POST http://localhost:3000/api/languages
content-type: application/json

{
    "enabled": "true"
}

### GetPeriodUnits (GET)
GET http://localhost:3000/api/periodunits

### GetPeriodUnits EN Only (GET)
GET http://localhost:3000/api/periodunits?langId=EN

### GetPeriodUnits (POST)
POST http://localhost:3000/api/periodunits
content-type: application/json

{
    "langId": "TH"
}

### GetPeriodUnit (GET)
GET http://localhost:3000/api/periodunits/search/1
### GetPeriodUnits (POST)
POST http://localhost:3000/api/periodunits/search
content-type: application/json

{
    "periodUnitId": 2
}

### GetLimitUnits (GET)
GET http://localhost:3000/api/limitunits

### GetLimitUnits EN Only (GET)
GET http://localhost:3000/api/limitunits?langId=EN

### GetLimitUnits (POST)
POST http://localhost:3000/api/limitunits
content-type: application/json

{
    "langId": "TH"
}

### GetLimitUnit (GET)
GET http://localhost:3000/api/limitunits/search/1
### GetLimitUnit (POST)
POST http://localhost:3000/api/limitunits/search
content-type: application/json

{
    "limitUnitId": 2
}

### GetMemberTypes (GET)
GET http://localhost:3000/api/membertypes

### GetMemberTypes EN Only (GET)
GET http://localhost:3000/api/membertypes?langId=EN

### GetMemberTypes (POST)
POST http://localhost:3000/api/membertypes
content-type: application/json

{
    "langId": "TH"
}

### GetMemberType (GET)
GET http://localhost:3000/api/membertypes/search/100
### GetMemberType (POST)
POST http://localhost:3000/api/membertypes/search
content-type: application/json

{
    "memberTypeId": 200
}

### GetDeviceTypes (GET)
GET http://localhost:3000/api/devicetypes

### GetDeviceTypes EN Only (GET)
GET http://localhost:3000/api/devicetypes?langId=EN

### GetDeviceTypes (POST)
POST http://localhost:3000/api/devicetypes
content-type: application/json

{
    "langId": "TH"
}

### GetDeviceType (GET)
GET http://localhost:3000/api/devicetypes/search/103
### GetDeviceType (POST)
POST http://localhost:3000/api/devicetypes/search
content-type: application/json

{
    "deviceTypeId": 101
}

### GetLicenseTypes (GET)
GET http://localhost:3000/api/licensetypes

### GetLicenseTypes EN Only (GET)
GET http://localhost:3000/api/licensetypes?langId=EN

### GetLicenseTypes (POST)
POST http://localhost:3000/api/licensetypes
content-type: application/json

{
    "langId": "TH"
}

### GetLicenseFeatures (GET)
GET http://localhost:3000/api/licensefeatures

### GetLicenseFeatures EN Only (GET)
GET http://localhost:3000/api/licensefeatures?langId=EN&licenseTypeId=1

### GetLicenseFeatures (POST)
POST http://localhost:3000/api/licensefeatures
content-type: application/json

{
    "langId": "TH"
}

### GetCustomers (GET)
GET http://localhost:3000/edl/api/customers

### GetCustomers EN Only (GET)
GET http://localhost:3000/edl/api/customers?langId=EN

### GetCustomers (POST)
POST http://localhost:3000/edl/api/customers
content-type: application/json

{
    "langId": "TH"
}

### GetCustomer (GET)
GET http://localhost:3000/edl/api/customers/search/EDL-C2020050001
### GetCustomer (POST)
POST http://localhost:3000/edl/api/customers/search
content-type: application/json

{
    "customerId": "EDL-C2020050001"
}

### GetUserInfos (GET)
GET http://localhost:3000/edl/api/users

### GetUserInfos EN Only (GET)
GET http://localhost:3000/edl/api/users?langId=EN

### GetUserInfos (POST)
POST http://localhost:3000/edl/api/users
content-type: application/json

{
    "langId": "TH"
}

### GetUserInfo (GET)
GET http://localhost:3000/edl/api/users/search/EDL-U20200502001

### GetUserInfo (POST)
POST http://localhost:3000/edl/api/users/search
content-type: application/json

{
    "userId": "EDL-U20200502001"
}

