### Getlanguages
POST http://localhost:3000/api/languages
content-type: application/json

{

}

### GetPeriodUnits (GET)
GET http://localhost:3000/api/periodunits

### GetPeriodUnits EN Only (GET)
GET http://localhost:3000/api/periodunits?langId=EN

### GetPeriodUnits (POST)
POST http://localhost:3000/api/periodunits
content-type: application/json

{
    "langId": "TH"
}

### GetPeriodUnit

### GetLimitUnits

### Get Limit Unit

### GetMemberTypes (GET)
GET http://localhost:3000/api/membertypes

### GetMemberTypes EN Only (GET)
GET http://localhost:3000/api/membertypes?langId=EN

### GetMemberTypes (POST)
POST http://localhost:3000/api/membertypes
content-type: application/json

{
    "langId": "TH"
}


### Get Member Type

### Get Device Types

### Get Device Type

### Get Customers

### Get Customer

### Get UserInfos

### Get UserInfo

