### Getlanguages
POST http://localhost:3000/api/languages
content-type: application/json

{

}

### GetPeriodUnits (GET)
GET http://localhost:3000/api/periodunits

### GetPeriodUnits EN Only (GET)
GET http://localhost:3000/api/periodunits?langId=EN

### GetPeriodUnits (POST)
POST http://localhost:3000/api/periodunits
content-type: application/json

{
    "langId": "TH"
}

### GetPeriodUnit

### GetLimitUnits (GET)
GET http://localhost:3000/api/limitunits

### GetLimitUnits EN Only (GET)
GET http://localhost:3000/api/limitunits?langId=EN

### GetLimitUnits (POST)
POST http://localhost:3000/api/limitunits
content-type: application/json

{
    "langId": "TH"
}

### GetLimitUnit

### GetMemberTypes (GET)
GET http://localhost:3000/api/membertypes

### GetMemberTypes EN Only (GET)
GET http://localhost:3000/api/membertypes?langId=EN

### GetMemberTypes (POST)
POST http://localhost:3000/api/membertypes
content-type: application/json

{
    "langId": "TH"
}


### GetMemberType

### GetDeviceTypes (GET)
GET http://localhost:3000/api/devicetypes

### GetDeviceTypes EN Only (GET)
GET http://localhost:3000/api/devicetypes?langId=EN

### GetDeviceTypes (POST)
POST http://localhost:3000/api/devicetypes
content-type: application/json

{
    "langId": "TH"
}

### Get Device Type

### Get Customers

### Get Customer

### Get UserInfos

### Get UserInfo

