### GetDevices (GET)
GET http://localhost:3000/customers/api/devices?customerId=EDL-C2020050001

### GetDevices (POST)
POST http://localhost:3000/customers/api/devices
content-type: application/json

{
    "langId": "TH",
    "customerId": "EDL-C2020050001"
}

### GetDevice (GET)
GET http://localhost:3000/customers/api/devices/search/D0001?customerId=EDL-C2020050001

### GetDevice (POST)
POST http://localhost:3000/customers/api/devices/search
content-type: application/json

{
    "customerId": "EDL-C2020050001",
    "deviceId": "D0002"
}
