### GetMemberInfos (GET)
GET http://localhost:3000/customers/api/members?customerId=EDL-C2020050001

### GetMemberInfos (POST)
POST http://localhost:3000/customers/api/members
content-type: application/json

{
    "langId": "TH",
    "customerId": "EDL-C2020050001"
}

### GetMemberInfo (GET)
GET http://localhost:3000/customers/api/members/search/M00001?customerId=EDL-C2020050001

### GetMemberInfo (POST)
POST http://localhost:3000/customers/api/members/search
content-type: application/json

{
    "customerId": "EDL-C2020050001",
    "memberId": "M00002"
}
