### Get Question sets
POST http://localhost:3000/customer/api/question/set
content-type: application/json

{
    "customerId": "EDL-C2020030001"
}

### Get Question set



#### Get Question Slides

POST http://localhost:3000/customer/api//question/slide
content-type: application/json

{
    "langId": null,
    "customerId": "EDL-C2020030001",
    "qSetId": "QS00001"
}

#### Get Question Slide



### Get Question Slide Items



### Get Question Slide Item

